### ISSUE TITLE
Complete image creation pipeline for manufacturing

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-gatewayrs#19]
**Acceptance criteria**
- Gateway container should use the same [base image](https://github.com/NebraLtd/hm-gatewayrs/blob/ff53631945bfc5755f0113f36b78c96525397d70/Dockerfile#L4) as hm-config and hm-diag.
- Output of hotspot-production-images starts and shows up in Balena.

**Comment by marvinmarnold** [comment]
@NebraLtd/device-team we agreed to move this out of the current sprint, correct?
