### ISSUE TITLE
Implement standardized build pipeline based on existing repos

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/hm-gatewayrs#25]
As a user of this repository, any new push should result in workflow triggers that do linting and dockerfile builds.
- cleanup the dockerfile build and startup script.
- verify that gateway miner runs on the device with ecc.
- update workflow trigger similar to hm-miner

**Acceptance Criterion**
- a new release of [upstream gateway-rs](https://github.com/helium/gateway-rs) results in auto bumping the dockerfile and corresponding dispatch to helium-miner-software
- Linting workflow actions for dockerfile, code, spellcheck and security. Copy linting settings from hm-confing and hotspot-production-tool.
- docker builds on every push.
- Add CODEOWNERS and CONTRIBUTING. Copy from existing repos.
  - Device team should be code owners.

**Comment by marvinmarnold** [comment]
@pritamghanghas FYI I just updated the AC
