### ISSUE TITLE
spike: investigate gateway-rs build to use.

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/hm-gatewayrs#30]
We are using [rasp01.deb](https://github.com/NebraLtd/hm-gatewayrs/blob/main/Dockerfile#L13) from gateway-rs releases. This will work only on raspberry pi boards but not on rock pi. On Rockpi boards, the binary just hangs up.

if we are using pi zero 2 W for light miners.  I think, we can just pick up rasp234.deb build which should work on all our current arm boards and close this issue.

**Acceptance criteria**
- List of gateway-rs build to use for ROCK PI miner, radxa zero, and rpi light miner, rpi indoor miner.
- [ ] Point helium-miner-software update [task](https://github.com/NebraLtd/helium-miner-software/blob/master/.github/workflows/update-miner.yml) to correct image
- [ ] List our products in [upstream repo](https://github.com/helium/gateway-rs#supported-platforms)

**Comment by shawaj** [comment]
We are using pi zero w. Original one armv6.

So we need to use raspi01 and this works on aarch64 as well

**Comment by pritamghanghas** [comment]
@shawaj I checked this again. The build that we have currently in hm-gatewayrs alpha23-raspi01.deb doesn't work on rockpi but raspi234 does work. It just hangs up. Works fine on raspberrys.

**Comment by shawaj** [comment]
I guess we will need to have both supported based on variant ID?

**Comment by marvinmarnold** [comment]
@posterzh what still needs to be done here?

**Comment by shawaj** [comment]
Closing as this was fixed in #35
