### ISSUE TITLE
need ability to pull frequency plan from miner / gateway-rs

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-gatewayrs#6]
currently, we have an environment variable set for REGION_OVERRIDE which determines the frequency plan and by extension the region in the settings.toml file.

At some point, it should be possible to get the frequency plan from the asserted location of the miner from the gateway-rs application.

Once this is possible, we need to implement this functionality here too

Relates to https://github.com/helium/gateway-rs/issues/43

**Comment by shawaj** [comment]
This is now added in https://github.com/helium/gateway-rs/pull/193

**Comment by pritamghanghas** [comment]
this will not require any action in this repo. We can close this.
